export const APP_NAME = "betha-tester-xd";

export const PAGE_HOME_CONTROLLER = 'PAGE_HOME_CONTROLLER';
export const PAGE_SIGNIN_CONTROLLER = 'PAGE_SIGNIN_CONTROLLER';
export const PAGE_SIGNUP_CONTROLLER = 'PAGE_SIGNUP_CONTROLLER';